name: Export to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm install

      - name: Building and exporting
        run: npm run build

      - name: Deploying
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: github-pages
          folder: out